// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDaF0huy9l2A7Cz1Oc4rJnEPsYsrjTT7U',
    appId: '1:524387842426:android:deaefa159697b3c1e7bec3',
    messagingSenderId: '524387842426',
    projectId: 'browniesbites-ac44e',
    storageBucket: 'browniesbites-ac44e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4pn-oDqjCEbyDjfDLipH5Bmf0pYk-i8s',
    appId: '1:524387842426:ios:35a915ab28630aace7bec3',
    messagingSenderId: '524387842426',
    projectId: 'browniesbites-ac44e',
    storageBucket: 'browniesbites-ac44e.firebasestorage.app',
    iosBundleId: 'com.codeforany.foodDelivery',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDutPLiaBlIX0QsjFDVOJlympXItzZMc5M',
    appId: '1:524387842426:web:a4239bc82eb52a6ce7bec3',
    messagingSenderId: '524387842426',
    projectId: 'browniesbites-ac44e',
    authDomain: 'browniesbites-ac44e.firebaseapp.com',
    storageBucket: 'browniesbites-ac44e.firebasestorage.app',
    measurementId: 'G-GEZNMS5DFF',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4pn-oDqjCEbyDjfDLipH5Bmf0pYk-i8s',
    appId: '1:524387842426:ios:bc3400753c57700ae7bec3',
    messagingSenderId: '524387842426',
    projectId: 'browniesbites-ac44e',
    storageBucket: 'browniesbites-ac44e.firebasestorage.app',
    iosBundleId: 'Broniesbites',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDutPLiaBlIX0QsjFDVOJlympXItzZMc5M',
    appId: '1:524387842426:web:bb417dc48c7fa138e7bec3',
    messagingSenderId: '524387842426',
    projectId: 'browniesbites-ac44e',
    authDomain: 'browniesbites-ac44e.firebaseapp.com',
    storageBucket: 'browniesbites-ac44e.firebasestorage.app',
    measurementId: 'G-N2M007F25N',
  );

}